const express=require('express')
const fs=require('fs')
const path=require('path')
const app=express()
const cfg=require('./set.json')
const schoolApi=require('./src/api/school')
const scheduleApi=require('./src/api/schedule')
const icsApi=require('./src/api/ics')
app.use(express.json())
app.use(express.static(path.join(__dirname,'public')))
app.get('/api/school/search',schoolApi.search)
app.get('/api/schedule',scheduleApi.get)
app.get('/api/ics',icsApi.make)
app.listen(cfg.port)
